INSERT INTO Rating VALUES (1, 'G');
INSERT INTO Rating VALUES (2, 'PG');
INSERT INTO Rating VALUES (3, 'PG_13');
INSERT INTO Rating VALUES (4, 'R');
INSERT INTO Rating VALUES (5, 'NC-17');

INSERT INTO Genre VALUES (1, 'COMEDY');
INSERT INTO Genre VALUES (2, 'DRAMA');
INSERT INTO Genre VALUES (3, 'CARTOON');
INSERT INTO Genre VALUES (4, 'THRILLER');
INSERT INTO Genre VALUES (5, 'DOCUMENTARY');
INSERT INTO Genre VALUES (6, 'ACTION');
INSERT INTO Genre VALUES (7, 'FANTASY');
INSERT INTO Genre VALUES (8, 'MUSICAL');
INSERT INTO Genre VALUES (9, 'MYSTERY');

INSERT INTO Friendship_status VALUES (1, 'PENDING');
INSERT INTO Friendship_status VALUES (2, 'CONFIRMED');